Display roulettes separately in todo window
MidoriKami/DailyDuty pull request #36
Opened 2022-03-14 12:08 UTC by Sevii77

Display all roulettes separately instead if grouping them together into a single item

2022-03-14 17:57 UTC, MidoriKami requested changes
I would prefer to let users have the option to display the task as just the header.

2022-03-14 20:41 UTC, MidoriKami commented on DailyDuty/Modules/Daily/DutyRoulette.cs
> +        public void DrawTask(TaskColors colors, bool showCompletedTasks)
Also, might consider indenting the roulettes so visually the user can consider them all to be part of one module.

This I will leave to your discretion.

2022-03-14 21:17 UTC, Sevii77 commented on DailyDuty/Modules/Daily/DutyRoulette.cs
> +        public void DrawTask(TaskColors colors, bool showCompletedTasks)
I assume most people simply want to know the tasks which they haven't completed yet and what module it's from isn't of importance, which is why i decided on the current implementation.

2022-03-15 01:12 UTC, MidoriKami approved these changes

2022-03-15 01:18 UTC, merged